from typing import Tuple
from matplotlib.axis import Axis
import numpy as np


def phaser_curve(x: complex, y: complex, n: int = 100) -> Tuple[np.ndarray, np.ndarray]:
    """
    Generate phaser curve

    Example:
        phaser_curve(_xy_light)

    Parameters:
        x: complex
            x component of light
        y: complex
            y component of light
        n: int
          curve point count.

    Returns: Tuple[np.ndarray, np.ndarray]
        (x, y) coordinates for the plot

    """
    omega = np.linspace(0, 2 * np.pi, n + 1)
    return np.real(x * np.exp(1j * omega)), np.imag(1j * y * np.exp(1j * omega))


def Phaser_Preset(ax: Axis, light: Tuple[complex, complex], color="red", stops=[0.125, 0.375, 0.625, 0.875]):
    """
    Plot phaser

    Example:
        phaser_plot(_plot_ax, pol_curve, color='red', stops=[0.125, 0.375, 0.625, 0.875]):

    Parameters:
        _plot_ax:
            plot axis
        pol_curve:
            phaser curve point (generated by phaser_curve)
        color:
            color
        stops:
            arrow head locations

    """
    phs_curve = phaser_curve(*light)
    phs_plot = ax.plot(phs_curve[0], phs_curve[1], color=color)
    n = phs_curve[0].shape[0]
    for _stop in stops:
        stop = int(_stop * n) + 1
        ax.arrow(phs_curve[0][stop + 0], phs_curve[1][stop + 0], phs_curve[0][stop + 1] - phs_curve[0][stop + 0], phs_curve[1][stop + 1] - phs_curve[1][stop + 0], shape="full", lw=0, length_includes_head=True, head_width=0.15, color=color)
